apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-connect
  namespace: kchernjak-338571
data:
  clickhouse_sink_connector.properties: |
    name=clickhouse-connect
    connector.class=com.clickhouse.kafka.connect.ClickHouseSinkConnector
    tasks.max=1
    errors.retry.timeout=60
    ssl=false
    value.converter=org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable=false
    exactlyOnce=true
    database=sensor_storage
    hostname=clickhouse-server-0.clickhouse-server-service
    port=8123
    username=default
    password=12345
    topics=sensors_data

  run.sh: |
    #!/bin/bash
    cd /opt/bitnami/kafka
    bin/connect-standalone.sh config/connect-standalone.properties config/clickhouse_sink_connector.properties
