# TODO: Need healthcheck that zookeeper and clickhouse are ready
# TODO: Need command to start kafka connect
# Configuration reference: https://github.com/bitnami/containers/blob/main/bitnami/kafka/README.md
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-service
  namespace: kchernjak-338571
  labels:
    app: kafka-connect

spec:
  selector:
    app: kafka-connect
  clusterIP: "None"
  ports:
  - name: http
    port: 9092
    protocol: TCP
  - name: controller
    port: 9093
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-connect
  namespace: kchernjak-338571
  labels:
    app: kafka-connect

spec:
  serviceName: "kafka-connect"
  updateStrategy:
    type: RollingUpdate
  replicas: 1 # TODO: I want 2 or more
  selector:
    matchLabels:
      app: kafka-connect  # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: kafka-connect  # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: kafka-connect
        image:  kainrehck/advanced_db:kafka-clickhouse-connector_x86
        imagePullPolicy: IfNotPresent
        # command: ["bash"]
        # args: ["/home/run.sh"]
        ports:
        - containerPort: 9093
        - containerPort: 9092
        env:
        - name: KAFKA_CFG_ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "zookeeper-0.zookeeper-service:2181"
        - name: KAFKA_CFG_ZOOKEEPER_PROTOCOL
          value: "PLAINTEXT"
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "1Gi"
        volumeMounts:
        - name: logs
          mountPath: /var/lib/kafka/data
        - name: clickhouse-sink-connector-config
          mountPath: /opt/bitnami/kafka/config/clickhouse_sink_connector.properties
          subPath: clickhouse_sink_connector.properties
        - name: clickhouse-sink-connector-config
          mountPath: /home/run.sh
          subPath: run.sh
      volumes:
        - name: clickhouse-sink-connector-config
          configMap:
            name: kafka-connect
  volumeClaimTemplates:
  - metadata:
      name: logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: "2Gi"
        limits:
          storage: "2Gi"