apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse-server
  namespace: kchernjak-338571
  labels:
    app: clickhouse-server

spec:
  updateStrategy:
    type: RollingUpdate  
  serviceName: "clickhouse-server-service"
  # minReadySeconds: 60
  replicas: 4
  selector:
    matchLabels:
      app: clickhouse-server  # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: clickhouse-server  # has to match .spec.selector.matchLabels
    spec:
      # terminationGracePeriodSeconds: 60
      initContainers:
      - name: init-configs
        image: busybox:1.33.0
        imagePullPolicy: IfNotPresent
        command: ['sh', '/tmp/conf.sh']
        env:
        - name: POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: configs-source
          mountPath: /tmp/
        - name: configs-target
          mountPath: /var/tmp
        - name: database-initialization
          mountPath: /var/tmp/database-initialization
      containers:
      - name: clickhouse-server
        image: clickhouse/clickhouse-server:latest   # 23.11.2.11 version
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8123
        - containerPort: 9000
        - containerPort: 9009
        env:
        - name: CLICKHOUSE_PASSWORD
          value: "12345"  # Change this to your desired password
        - name: CLICKHOUSE_KEEPER_MAP_PATH_PREFIX
          value: "test_keeper_map"
        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        volumeMounts:
        - name: configs-target
          mountPath: /etc/clickhouse-server/conf.d
        - name: database-initialization
          mountPath: /docker-entrypoint-initdb.d
        - name: clickhouse-server-storage
          mountPath: /var/lib/clickhouse
      volumes:
      - name: configs-source
        configMap:
          name: clickhouse-server
      - name: configs-target
        emptyDir: {}
      - name: database-initialization
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: clickhouse-server-storage
    spec:
      accessModes: [ "ReadWriteOncePod" ]
      resources:
        requests:
          storage: "50Gi"
        limits:
          storage: "50Gi"