apiVersion: v1
kind: Service
metadata:
  name: clickhouse-server
  namespace: kchernjak-338571
  labels:
    app: clickhouse-server

spec:
  type: NodePort  # TODO: maube change to load balancer?
  selector:
    app: clickhouse-server
  ports:
  - name: http
    port: 8123
    protocol: TCP
  - name: client
    port: 9000
    protocol: TCP
  - name: replication
    port: 9009
    protocol: TCP
